=== starlingx/config/sysinv/sysinv/sysinv/etc/sysinv/profileSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="Processor">
    <xs:attribute type="xs:byte" name="index" />
    <xs:attribute type="xs:byte" name="numberOfCores" />
  </xs:complexType>
  <xs:complexType name="CPUProfile">
    <xs:sequence>
      <xs:element name="processor" minOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element type="xs:byte" name="numberOfProcessor" />
            <xs:element type="xs:byte" name="coresPerProcessor" />
            <xs:element type="xs:boolean" name="hyperThreading" minOccurs="0" maxOccurs="1" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="platformCores" minOccurs="1">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="processor" type="Processor" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="vswitchCores" minOccurs="0">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="processor" type="Processor" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="sharedCores" minOccurs="0">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="processor" type="Processor" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>
  <xs:complexType name="memoryAllocation">
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element name="processor" type="processorMemory" />
      </xs:sequence>
  </xs:complexType>
  <xs:complexType name="processorMemory">
	<xs:attribute type="xs:nonNegativeInteger" name="index" use="required" />
	<xs:attribute type="xs:nonNegativeInteger" name="size" use="required" />
  </xs:complexType>
  <xs:complexType name="MemoryProfile">
    <xs:sequence>
      <xs:element type="xs:byte" name="numberOfProcessor" />
      <xs:element name="platformReservedMiB" type="memoryAllocation" minOccurs="0" maxOccurs="1"/>
      <xs:element name="vmHugePages2M" type="memoryAllocation" minOccurs="0" maxOccurs="1"/>
      <xs:element name="vmHugePages1G" type="memoryAllocation" minOccurs="0" maxOccurs="1"/>
      <xs:element name="vsHugePagesNr" type="memoryAllocation" minOccurs="0" maxOccurs="1"/>
      <xs:element name="vsHugePagesSz" type="memoryAllocation" minOccurs="0" maxOccurs="1"/>
	</xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>
  <xs:simpleType name="TxPolicy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="layer3+4" />
      <xs:enumeration value="layer2+3" />
      <xs:enumeration value="layer2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="AeModePolicy">
    <xs:attribute name="txPolicy" type="TxPolicy" />
  </xs:complexType>
  <xs:complexType name="AeMode">
    <xs:choice minOccurs="1" maxOccurs="1">
      <xs:element name="activeStandby" />
      <xs:element name="balanced" type="AeModePolicy" />
      <xs:element name="ieee802.3ad" type="AeModePolicy" />
    </xs:choice>
  </xs:complexType>
  <xs:simpleType name="Ipv4Mode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="disabled" />
      <xs:enumeration value="static" />
      <xs:enumeration value="dhcp" />
      <xs:enumeration value="pool" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Ipv6Mode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="disabled" />
      <xs:enumeration value="static" />
      <xs:enumeration value="auto" />
      <xs:enumeration value="link-local" />
      <xs:enumeration value="pool" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="interface">
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="interfaces">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
	  <xs:element type="interface" name="interface" >
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="providerNetwork">
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="providerNetworks">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
	  <xs:element type="providerNetwork" name="providerNetwork" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="IpPool">
    <xs:attribute name="name" use="required">
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="ipv4">
    <xs:sequence>
      <xs:element name="pool" type="IpPool" minOccurs="0" maxOccurs="1">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="mode" type="Ipv4Mode" use="required" />
  </xs:complexType>

  <xs:complexType name="ipv6">
    <xs:sequence>
      <xs:element name="pool" type="IpPool" minOccurs="0" maxOccurs="1">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="mode" type="Ipv6Mode" use="required" />
  </xs:complexType>

  <xs:complexType name="dataclassNetwork">
    <xs:sequence>
      <xs:element name="providerNetworks" type="providerNetworks" minOccurs="1" maxOccurs="unbounded">
      </xs:element>
      <xs:element name="ipv4" type="ipv4" minOccurs="1" maxOccurs="1">
	  </xs:element>
	  <xs:element name="ipv6" type="ipv6" minOccurs="1" maxOccurs="1">
	  </xs:element>
      <xs:element name="routes" type="routes" minOccurs="0" maxOccurs="1">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="externalNetwork">
  </xs:complexType>

  <xs:complexType name="pciPassthrough">
    <xs:sequence>
      <xs:element name="providerNetworks" type="providerNetworks" minOccurs="1" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="pciSriov">
    <xs:sequence>
      <xs:element name="providerNetworks" type="providerNetworks" minOccurs="1" maxOccurs="unbounded">
      </xs:element>
    </xs:sequence>
    <xs:attribute name="virtualFunctions" type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="virtualFunctionDriver" type="xs:string" />
    <xs:attribute name="maxTxRate" type="xs:nonNegativeInteger" />
  </xs:complexType>

  <xs:complexType name="route">
    <xs:attribute name="network" type="xs:string" />
    <xs:attribute name="metric" type="xs:integer" />
    <xs:attribute name="gateway" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="routes">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="route" type="route">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="pciAddress">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9a-fA-F]{1,4}[:][0-9a-fA-F]{1,2}[:][0-9a-fA-F]{1,2}[.][0-9a-fA-F]" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="pciClass">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Ethernet controller" />
      <xs:enumeration value="Network controller" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ethernetInterface">
	<xs:sequence>
        <xs:element name="port" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="name" use="optional" />
            <xs:attribute name="pciAddress" type="pciAddress" use="optional" />
            <xs:attribute name="class"  type="pciClass" use="required" />
            <xs:attribute name="device" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="networks" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element name="dataclassNetwork" type="dataclassNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="clusterhostNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="mgmtNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="oamNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="pciPassthrough" type="pciPassthrough" maxOccurs="1">
                </xs:element>
                <xs:element name="pciSriov" type="pciSriov" maxOccurs="1">
                </xs:element>
              </xs:choice>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
	</xs:sequence>
	<xs:attribute name="ifName" type="xs:string" use="required" />
    <xs:attribute name="mtu" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:simpleType name="VlanId">
    <xs:restriction base="xs:short">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="4094" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="vlanInterface">
	<xs:sequence>
      <xs:element name="networks">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element name="mgmtNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="oamNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="dataclassNetwork" type="dataclassNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="clusterhostNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
              </xs:choice>
            </xs:sequence>
        </xs:complexType>
      </xs:element>
	</xs:sequence>
	<xs:attribute name="ifName" type="xs:string" use="required" />
    <xs:attribute name="interface" type="xs:string" use="required" />
	<xs:attribute name="vlanId" type="VlanId" use="required"/>
    <xs:attribute name="mtu" type="xs:positiveInteger" use="required" />
  </xs:complexType>

  <xs:complexType name="aeInterface">
	<xs:sequence>
        <xs:element name="networks" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:choice minOccurs="1" maxOccurs="2">
                <xs:element name="mgmtNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="oamNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="dataclassNetwork" type="dataclassNetwork" maxOccurs="1">
                </xs:element>
                <xs:element name="clusterhostNetwork" type="externalNetwork" maxOccurs="1">
                </xs:element>
              </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="interfaces" type="interfaces">
      </xs:element>
      <xs:element name="aeMode" type="AeMode" minOccurs="1" maxOccurs="1">
      </xs:element>
	</xs:sequence>
	<xs:attribute name="ifName" type="xs:string" use="required" />
    <xs:attribute name="mtu" type="xs:positiveInteger" use="required" />
  </xs:complexType>
  <xs:complexType name="InterfaceProfile">
    <xs:choice maxOccurs="unbounded">
	  <xs:element type="ethernetInterface" name="ethernetInterface">
	  </xs:element>
	  <xs:element type="vlanInterface" name="vlanInterface">
	  </xs:element>
	  <xs:element type="aeInterface" name="aeInterface">
	  </xs:element>
    </xs:choice>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <xs:simpleType name="volumeFunction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="osd" />
      <xs:enumeration value="journal" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Disk">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required" />
        <xs:attribute type="xs:positiveInteger" name="size" use="required" />
        <xs:attribute type="volumeFunction" name="volumeFunc" use="optional" />
        <xs:attribute type="xs:positiveInteger" name="journalSize" use="optional" />
        <xs:attribute type="xs:string" name="journalLocation" use="optional" />
        <xs:attribute type="xs:string" name="tier" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="StorageProfile">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="Disk" name="disk" minOccurs="0" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <xs:simpleType name="Lvm_vg_name">
    <xs:restriction base="xs:string">
      <xs:enumeration value="nova-local" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="Lvg">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="Lvm_vg_name" name="lvm_vg_name" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="LocalStorageProfile">
    <xs:sequence maxOccurs="unbounded">
      <xs:element type="Disk" name="disk" minOccurs="0" />
      <xs:element type="Lvg" name="lvg" minOccurs="0" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required" />
  </xs:complexType>

  <xs:element name="profiles">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="cpuProfile" type="CPUProfile" maxOccurs="unbounded" minOccurs="0" nillable="true" />
        <xs:element name="memoryProfile" type="MemoryProfile" maxOccurs="unbounded" minOccurs="0" nillable="true" />
        <xs:element name="interfaceProfile" type="InterfaceProfile" maxOccurs="unbounded" minOccurs="0" nillable="true" />
        <xs:element name="storageProfile" type="StorageProfile" maxOccurs="unbounded" minOccurs="0" nillable="true" />
        <xs:element name="localstorageProfile" type="LocalStorageProfile" maxOccurs="unbounded" minOccurs="0" nillable="true" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== starlingx/config/sysinv/sysinv/sysinv/etc/sysinv/sampleProfile.xml
<?xml version="1.0" encoding="utf-8"?>
<profiles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="profileSchema.xsd">
	<!--This is a typical 2 processors by 10 physical cores compute node
	  Taken from HP380 -->
	<cpuProfile name="cpu-2x10">
		<processor>
			<!--number of processors on the server-->
			<numberOfProcessor>2</numberOfProcessor>
			<!--number of physical cores in each processor.
			Specify number of the physical cores here.
			To see logical core mapping, turn on the hyper-threading below-->
			<coresPerProcessor>10</coresPerProcessor>
			<!--use optional hyperThreading to enable hyper-thread to the -->
			<!--profile. Enabling hyper-threading will make the profile looks-->
			<!--like what it is as if the host has it hyper-threading enabled. -->
			<hyperThreading>false</hyperThreading>
		</processor>

		<!--platformCores section defines physical cores assign to platform functions on each processor -->
		<platformCores>
			<!--Each processor tag defines number of physical cores to be assigned to platform function on
			a processor indicated by the index.
			processor index starts from 0 to numberOfProcessor -1.
			Each processor (indicated by index) should only appear once-->
			<processor index="0" numberOfCores="1"></processor>
		</platformCores>

		<!--vswitchCores section defines physical cores assign to vswitch functions on each processor
		    This setting only apply to the compute nodes. -->
		<vswitchCores>
			<!--Each processor tag defines number of physical cores to be assigned to vswitch function on
			a processor indicated by the index.
			processor index starts from 0 to numberOfProcessor -1.
			Each processor (indicated by index) should only appear once-->
			<processor index="0" numberOfCores="2"></processor>
		</vswitchCores>

		<!--remaining cores on each processor are assigned to guest VMs-->
	</cpuProfile>

	<!--this setup is taken from HP380 -->
	<memoryProfile name="mem-profile">
		<!--number of CPUs on the motherboard-->
		<numberOfProcessor>2</numberOfProcessor>

		<!--platformReservedMiB section defines the memory to be reserved for platform functions-->
		<platformReservedMiB>
			<!--Each processor tag defines number of physical cores to be assigned to vswitch function on
			a processor indicated by the index.
			processor index starts from 0 to numberOfProcessor -1.
			Each processor (indicated by index) should only appear once.
			The size is in MB-->
			<processor index="0" size="4000"></processor>
			<processor index="1" size="2000"></processor>
		</platformReservedMiB>

		<!--vmHugePages2M section defines number of 2M bytes huge page assigned to each processor-->
		<vmHugePages2M>
			<!--Each processor tag defines number of physical cores to be assigned to vswitch function on
			a processor indicated by the index.
			processor index starts from 0 to numberOfProcessor -1.
			Each processor (indicated by index) should only appear once. -->
			<processor index="0" size="29096"></processor>
			<processor index="1" size="30129"></processor>
		</vmHugePages2M>

		<!--vmHugePages1G section defines number of 1G bytes huge page assigned to each processor-->
		<vmHugePages1G>
			<!--Each processor tag defines number of physical cores to be assigned to vswitch function on
			a processor indicated by the index.
			processor index starts from 0 to numberOfProcessor -1.
			Each processor (indicated by index) should only appear once. -->
			<processor index="0" size="0"></processor>
			<processor index="1" size="0"></processor>
		</vmHugePages1G>
	</memoryProfile>

        <!--This setup is taken from wildcat7_12-->
        <storageProfile name="storage-profile">
            <!--The disk tags below define each device,
            path: device path
            size: minimum size (in GiB)
            volumeFunc: volume function to be assigned to the device
                For 'osd' function:
                    journalSize: the size of the ceph journal in GiB, if absent defaults to journal_default_size in sysinv.conf
                    journalLocation: location of the journal partition, mandatory if multiple journal functions are defined,
                                     if absent defaults to the single available journal drive.
                If no device with journal function is configured then the journals for all OSDs will be collocated on the
                same device with the OSD data (partition #1 is for the data and partition #2 for the journl).
                In this case the size of the journal will be journal_default_size.-->
            <disk path="/dev/sdb" size="223" volumeFunc="osd" journalSize="2" journalLocation="/dev/sdd" />
            <disk path="/dev/sdc" size="223" volumeFunc="osd" journalLocation="/dev/sde" />
            <disk path="/dev/sdd" size="223" volumeFunc="journal" />
            <disk path="/dev/sde" size="223" volumeFunc="journal" />
        </storageProfile>

        <storageProfile name="storage-profile-coloc-no-tier">
            <!--The disk tags below define each device,
            path: device path
            size: minimum size (in GiB)
            volumeFunc: volume function to be assigned to the device
                For 'osd' function:
                    journalSize: the size of the ceph journal in GiB, if absent defaults to journal_default_size in sysinv.conf
                    journalLocation: location of the journal partition, mandatory if multiple journal functions are defined,
                                     if absent defaults to the single available journal drive.
                    tier: storage tier for OSDs. If this is not specified, then the
                          primary system default tier, 'storage', is used.
                If no device with journal function is configured then the journals for all OSDs will be collocated on the
                same device with the OSD data (partition #1 is for the data and partition #2 for the journl).
                In this case the size of the journal will be journal_default_size.
            -->
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-2.0" size="50" volumeFunc="osd"/>
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-3.0" size="50" volumeFunc="osd"/>
        </storageProfile>

        <storageProfile name="storage-profile-journal-no-tier">
            <!--The disk tags below define each device,
            path: device path
            size: minimum size (in GiB)
            volumeFunc: volume function to be assigned to the device
                For 'osd' function:
                    journalSize: the size of the ceph journal in GiB, if absent defaults to journal_default_size in sysinv.conf
                    journalLocation: location of the journal partition, mandatory if multiple journal functions are defined,
                                     if absent defaults to the single available journal drive.
                    tier: storage tier for OSDs. If this is not specified, then the
                          primary system default tier, 'storage', is used.
                If no device with journal function is configured then the journals for all OSDs will be collocated on the
                same device with the OSD data (partition #1 is for the data and partition #2 for the journl).
                In this case the size of the journal will be journal_default_size.
            -->
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-2.0" size="50" volumeFunc="osd"/>
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-3.0" size="50" volumeFunc="journal"/>
        </storageProfile>

        <storageProfile name="storage-profile-coloc-two-tiers">
            <!--The disk tags below define each device,
            path: device path
            size: minimum size (in GiB)
            volumeFunc: volume function to be assigned to the device
                For 'osd' function:
                    journalSize: the size of the ceph journal in GiB, if absent defaults to journal_default_size in sysinv.conf
                    journalLocation: location of the journal partition, mandatory if multiple journal functions are defined,
                                     if absent defaults to the single available journal drive.
                    tier: storage tier for OSDs. If this is not specified, then the
                          primary system default tier, 'storage', is used.
                If no device with journal function is configured then the journals for all OSDs will be collocated on the
                same device with the OSD data (partition #1 is for the data and partition #2 for the journl).
                In this case the size of the journal will be journal_default_size.
            -->
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-2.0" size="50" volumeFunc="osd" tier="storage"/>
            <disk path="/dev/disk/by-path/pci-0000:00:0d.0-ata-3.0" size="50" volumeFunc="osd" tier="gold"/>
        </storageProfile>

        <localstorageProfile name="localstorage-profile_localimage">
		<!--The disk tags below define each device,
		        node: device node
		        size: minimum size (in GiB).
                    The lvg tags below define the local volume group 
                        lvm_vg_name: local volume group name
                        instance_backing: image, or remote
                        concurrent_disk_operations: number of parallel I/O intensive disk operations
                -->
           <disk path="/dev/sdb" size="223" />
           <lvg lvm_vg_name="nova-local" instance_backing="image" concurrent_disk_operations="2" />
        </localstorageProfile>

        <localstorageProfile name="localstorage-profile_remote">
		<!--The disk tags below define each device,
		        node: device node
		        size: minimum size (in MB).
                    The lvg tags below define the local volume group
